package emperorfin.android.githubusers.ui.model.repo

import emperorfin.android.githubusers.domain.uilayer.event.output.repo.RepoUiModelParams
import emperorfin.android.githubusers.ui.model.repo.embedded.Owner
import emperorfin.android.githubusers.ui.model.repo.embedded.Permissions


/*
 * @Author: Francis Nwokelo (emperorfin)
 * @Date: Thursday 24th October, 2024.
 */




data class RepoUiModel private constructor(
    override val id: Long,
    override val nodeId: String,
    override val name: String,
    override val fullName: String,
    override val _private: Boolean?,
    override val owner: Owner,
    override val htmlUrl: String,
    override val description: String,
    override val fork: Boolean?,
    override val url: String,
    override val forksUrl: String,
    override val keysUrl: String,
    override val collaboratorsUrl: String,
    override val teamsUrl: String,
    override val hooksUrl: String,
    override val issueEventsUrl: String,
    override val eventsUrl: String,
    override val assigneesUrl: String,
    override val branchesUrl: String,
    override val tagsUrl: String,
    override val blobsUrl: String,
    override val gitTagsUrl: String,
    override val gitRefsUrl: String,
    override val treesUrl: String,
    override val statusesUrl: String,
    override val languagesUrl: String,
    override val stargazersUrl: String,
    override val contributorsUrl: String,
    override val subscribersUrl: String,
    override val subscriptionUrl: String,
    override val commitsUrl: String,
    override val gitCommitsUrl: String,
    override val commentsUrl: String,
    override val issueCommentUrl: String,
    override val contentsUrl: String,
    override val compareUrl: String,
    override val mergesUrl: String,
    override val archiveUrl: String,
    override val downloadsUrl: String,
    override val issuesUrl: String,
    override val pullsUrl: String,
    override val milestonesUrl: String,
    override val notificationsUrl: String,
    override val labelsUrl: String,
    override val releasesUrl: String,
    override val deploymentsUrl: String,
    override val createdAt: String,
    override val updatedAt: String,
    override val pushedAt: String,
    override val gitUrl: String,
    override val sshUrl: String,
    override val cloneUrl: String,
    override val svnUrl: String,
    override val homepage: String,
    override val size: Int,
    override val stargazersCount: Int,
    override val watchersCount: Int,
    override val language: String,
    override val hasIssues: Boolean?,
    override val hasProjects: Boolean?,
    override val hasDownloads: Boolean?,
    override val hasWiki: Boolean?,
    override val hasPages: Boolean?,
    override val hasDiscussions: Boolean?,
    override val forksCount: Int,
    override val mirrorUrl: String,
    override val archived: Boolean?,
    override val disabled: Boolean?,
    override val openIssuesCount: Int,
    override val license: String,
    override val allowForking: Boolean?,
    override val isTemplate: Boolean?,
    override val webCommitSignoffRequired: Boolean?,
    override val topics: List<String>,
    override val visibility: String,
    override val forks: Int,
    override val openIssues: Int,
    override val watchers: Int,
    override val defaultBranch: String,
    override val permissions: Permissions?
) : RepoUiModelParams {

    companion object {

        fun newInstance(
            id: Long,
            nodeId: String,
            name: String,
            fullName: String,
            private: Boolean?,
            owner: Owner,
            htmlUrl: String,
            description: String,
            fork: Boolean?,
            url: String,
            forksUrl: String,
            keysUrl: String,
            collaboratorsUrl: String,
            teamsUrl: String,
            hooksUrl: String,
            issueEventsUrl: String,
            eventsUrl: String,
            assigneesUrl: String,
            branchesUrl: String,
            tagsUrl: String,
            blobsUrl: String,
            gitTagsUrl: String,
            gitRefsUrl: String,
            treesUrl: String,
            statusesUrl: String,
            languagesUrl: String,
            stargazersUrl: String,
            contributorsUrl: String,
            subscribersUrl: String,
            subscriptionUrl: String,
            commitsUrl: String,
            gitCommitsUrl: String,
            commentsUrl: String,
            issueCommentUrl: String,
            contentsUrl: String,
            compareUrl: String,
            mergesUrl: String,
            archiveUrl: String,
            downloadsUrl: String,
            issuesUrl: String,
            pullsUrl: String,
            milestonesUrl: String,
            notificationsUrl: String,
            labelsUrl: String,
            releasesUrl: String,
            deploymentsUrl: String,
            createdAt: String,
            updatedAt: String,
            pushedAt: String,
            gitUrl: String,
            sshUrl: String,
            cloneUrl: String,
            svnUrl: String,
            homepage: String,
            size: Int,
            stargazersCount: Int,
            watchersCount: Int,
            language: String,
            hasIssues: Boolean?,
            hasProjects: Boolean?,
            hasDownloads: Boolean?,
            hasWiki: Boolean?,
            hasPages: Boolean?,
            hasDiscussions: Boolean?,
            forksCount: Int,
            mirrorUrl: String,
            archived: Boolean?,
            disabled: Boolean?,
            openIssuesCount: Int,
            license: String,
            allowForking: Boolean?,
            isTemplate: Boolean?,
            webCommitSignoffRequired: Boolean?,
            topics: List<String>,
            visibility: String,
            forks: Int,
            openIssues: Int,
            watchers: Int,
            defaultBranch: String,
            permissions: Permissions?
        ): RepoUiModel {
            return RepoUiModel(
                id = id,
                nodeId = nodeId,
                name = name,
                fullName = fullName,
                _private = private,
                owner = owner,
                htmlUrl = htmlUrl,
                description = description,
                fork = fork,
                url = url,
                forksUrl = forksUrl,
                keysUrl = keysUrl,
                collaboratorsUrl = collaboratorsUrl,
                teamsUrl = teamsUrl,
                hooksUrl = hooksUrl,
                issueEventsUrl = issueEventsUrl,
                eventsUrl = eventsUrl,
                assigneesUrl = assigneesUrl,
                branchesUrl = branchesUrl,
                tagsUrl = tagsUrl,
                blobsUrl = blobsUrl,
                gitTagsUrl = gitTagsUrl,
                gitRefsUrl = gitRefsUrl,
                treesUrl = treesUrl,
                statusesUrl = statusesUrl,
                languagesUrl = languagesUrl,
                stargazersUrl = stargazersUrl,
                contributorsUrl = contributorsUrl,
                subscribersUrl = subscribersUrl,
                subscriptionUrl = subscriptionUrl,
                commitsUrl = commitsUrl,
                gitCommitsUrl = gitCommitsUrl,
                commentsUrl = commentsUrl,
                issueCommentUrl = issueCommentUrl,
                contentsUrl = contentsUrl,
                compareUrl = compareUrl,
                mergesUrl = mergesUrl,
                archiveUrl = archiveUrl,
                downloadsUrl = downloadsUrl,
                issuesUrl = issuesUrl,
                pullsUrl = pullsUrl,
                milestonesUrl = milestonesUrl,
                notificationsUrl = notificationsUrl,
                labelsUrl = labelsUrl,
                releasesUrl = releasesUrl,
                deploymentsUrl = deploymentsUrl,
                createdAt = createdAt,
                updatedAt = updatedAt,
                pushedAt = pushedAt,
                gitUrl = gitUrl,
                sshUrl = sshUrl,
                cloneUrl = cloneUrl,
                svnUrl = svnUrl,
                homepage = homepage,
                size = size,
                stargazersCount = stargazersCount,
                watchersCount = watchersCount,
                language = language,
                hasIssues = hasIssues,
                hasProjects = hasProjects,
                hasDownloads = hasDownloads,
                hasWiki = hasWiki,
                hasPages = hasPages,
                hasDiscussions = hasDiscussions,
                forksCount = forksCount,
                mirrorUrl = mirrorUrl,
                archived = archived,
                disabled = disabled,
                openIssuesCount = openIssuesCount,
                license = license,
                allowForking = allowForking,
                isTemplate = isTemplate,
                webCommitSignoffRequired = webCommitSignoffRequired,
                topics = topics,
                visibility = visibility,
                forks = forks,
                openIssues = openIssues,
                watchers = watchers,
                defaultBranch = defaultBranch,
                permissions = permissions
            )
        }

    }

}
